version: '3.3'
services:
  db:
    image: postgres:12.4
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/prod.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    env_file:
      - ../backend/prod.env
    depends_on:
      - db

  frontend:
    image: abduev/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_value:/var/www/backend_static/
      - media_value:/var/www/backend_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - db

volumes:
  postgres_data:
  static_value:
  media_value: 